name: flutter_test_practice_2
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BSD
  # Android, IOS, Linux, macOS, WEB, Windows
  cupertino_icons: ^1.0.3

  # MIT
  # Android, IOS, Linux, macOS, WEB, Windows
  provider: ^6.0.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  assets:
    - assets/
